### ISSUE TITLE
write data pulling functions for the connectomes of interest - NeuPrint

### ISSUE THREAD

**Issue by pauladkisson** [neurodata/connectocross#8]
for the connectomes listed in the readme (roughly, exact ones may change)
- want a simple, clear script to pull necessary graph + metadata from wherever it's hosted online 
- saves that data to the format specified in #1 

Note: Sub-issue of #2 

Specifically, focus on datasets stored as NeuPrint files.

**Comment by bdpedigo** [comment]
Note: (I think) NeuPrint is a database, not exactly a "file"

**Comment by Jingyan230** [comment]
**Work plan**
- [ ] Read the [paper](https://www.biorxiv.org/content/10.1101/2020.01.21.911859v1)
- [ ] Try to understand the data in the [dataset](https://www.janelia.org/project-team/flyem/hemibrain)
- [ ] Write a simple, clear script to pull necessary graph + metadata from the dataset of [Drosophila adult brain chunk (hemibrain)](https://www.janelia.org/project-team/flyem/hemibrain)
- [ ] Saves the data to the format specified in [#1](https://github.com/neurodata/connectocross/issues/1)

**Comment by jovo** [comment]
https://www.biorxiv.org/content/10.1101/2020.01.21.911859v1

**Comment by bdpedigo** [comment]
https://www.biorxiv.org/content/10.1101/2020.08.29.273276v1
